account/urls.py
# -*- coding: utf8 -*-
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('dashboard/<int:action>',  views.MessageList.as_view()),
    path('login/<int:role>', views.Login.as_view()),
    path('logout/', views.Logout.as_view()),  
    path('user/', views.UserList.as_view()),
    path('user/create/', views.UserCreate.as_view()),    
    path('user/<int:pk>', views.UserDetail.as_view()),
    path('user/<int:pk>/update/', views.UserUpdate.as_view()), 
    path('user/<int:pk>/password/', views.UserPasswordUpdate.as_view()), 
    path('user/<int:pk>/teacher/', views.UserTeacher.as_view()),    
    #註冊學校
    path('school/create/', views.SchoolCreate.as_view()), 
    #私訊
    path('line/classmate/<int:classroom_id>/', views.LineClassmateList.as_view()),      
    path('line/<int:user_id>/<int:classroom_id>/create/', views.LineCreate.as_view()), 
    path('line/<int:pk>/', views.LineDetail.as_view()),    
]

bioread/urls.py
# -*- coding: utf8 -*-
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="homepage.html")),
    path('account/', include('account.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('annotate/', include('annotate.urls')),
]

teacher/urls.py
# -*- coding: utf8 -*-
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('classroom/', views.ClassroomList.as_view()),
    path('classroom/create/', views.ClassroomCreate.as_view()),    
    path('classroom/<int:pk>/update/', views.ClassroomUpdate.as_view()), 
    path('announce/<int:classroom_id>/create/', views.AnnounceCreate.as_view()),   
    #列出所有學生帳號
    path('student/list/', views.StudentList.as_view()),    	
	  #大量匯入帳號
    path('import/upload/', views.StudentUpload.as_view()),   	
    path('import/student/', views.StudentImport.as_view()),   
    # 分組
    path('group/<int:classroom_id>/', views.GroupList.as_view()),
    path('group/add/<int:classroom_id>/', views.GroupCreate.as_view()),  
    path('group/edit/<int:classroom_id>/<int:pk>/', views.GroupUpdate.as_view()),    
    path('group/make/',views.make),   
    path('group/make2/<int:group_id>/<int:action>/', views.make2),  
    #設定助教
    path('classroom/assistant/<int:classroom_id>/', views.ClassroomAssistant.as_view()),  
    path('classroom/assistant/add/<int:classroom_id>/', views.AssistantList.as_view()),    
    path('assistant/', views.AssistantClassroomList.as_view()),  
    path('assistant/make/', views.assistant_make),  
    # 討論區
    #path('forum/<int:categroy>/<int:categroy_id>', views.ForumAllListView.as_view()),  
    #url(r'^forum/show/(?P<forum_id>\d+)/$', login_required(views.forum_show), name='forum-show'),    
    path('forum/<int:classroom_id>/', views.ForumListView.as_view()),
    path('forum/add/<int:classroom_id>/', views.ForumCreateView.as_view()),
    path('forum/edit/<int:classroom_id>/<int:pk>/', views.ForumEditUpdate.as_view()),     
    path('forum/class/<int:forum_id>/', views.ForumClassList.as_view()),      
    path('forum/class/switch/', views.forum_switch),      
    path('forum/deadline/<int:classroom_id>/<int:pk>/', views.ForumDeadlineUpdate.as_view()),  
    path('forum/deadline/set/', views.forum_deadline_set), 
    path('forum/deadline/date/', views.forum_deadline_date),   
    path('forum/content/<int:forum_id>/', views.ForumContentList.as_view()), 
    path('forum/content/add/<int:forum_id>/', views.ForumContentCreate.as_view()),
    path('forum/content/delete/<int:forum_id>/<int:content_id>/', views.forum_delete),   
    #url(r'^forum/content/edit/(?P<forum_id>\d+)/(?P<content_id>\d+)/$', login_required(views.forum_edit), name='forum-content-edit'),      
    path('forum/download/<int:content_id>/', views.forum_download),  


    #url(r'^forum/export/(?P<classroom_id>\d+)/(?P<forum_id>\d+)/$', login_required(views.forum_export), name='forum-export'),   
    #url(r'^forum/grade/(?P<classroom_id>\d+)/(?P<action>\d+)/$', login_required(views.forum_grade), name='forum-grade'),   
  
]

teacher/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime, timedelta

# 班級
class Classroom(models.Model):
    # 班級名稱
    name = models.CharField(max_length=30)
    # 選課密碼
    password = models.CharField(max_length=30)
    # 授課教師
    teacher_id = models.IntegerField(default=0)
    # 學習領域
    domains = models.TextField(default='')
    #年級
    levels = models.TextField(default='')

    @property
    def teacher(self):
        return User.objects.get(id=self.teacher_id)

#匯入
class ImportUser(models.Model):
	  username = models.CharField(max_length=50, default="")
	  first_name = models.CharField(max_length=50, default="")
	  password = models.CharField(max_length=50, default="")
	  email = models.CharField(max_length=100, default="")

class ClassroomGroup(models.Model):
    # 班級
    classroom_id = models.IntegerField(default=0)
    #分組名稱
    title = models.CharField(max_length=250,null=True,blank=True)
    #小組數目
    numbers = models.IntegerField(default=6)
    #開放分組
    opening = models.BooleanField(default=True)
		#分組方式
    assign = models.IntegerField(default=0)

    def __unicode__(self):
        return self.classroom_id

#班級助教
class Assistant(models.Model):
    classroom_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)

#討論區
class FWork(models.Model):
    title = models.CharField(max_length=250,verbose_name= '討論主題')
    teacher_id = models.IntegerField(default=0)
    classroom_id = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now)
    domains = models.TextField(default='')
    levels = models.TextField(default='')

def get_deadline():
    return datetime.today() + timedelta(days=14)

class FClass(models.Model):
    forum_id = models.IntegerField(default=0)
    classroom_id =  models.IntegerField(default=0)
    publication_date = models.DateTimeField(default=timezone.now)
    deadline = models.BooleanField(default=False)
    deadline_date = models.DateTimeField(default=get_deadline)

    def __unicode__(self):
        return str(self.forum_id)

class FContent(models.Model):
    forum_id =  models.IntegerField(default=0)
    types = models.IntegerField(default=0)
    title = models.CharField(max_length=250,null=True,blank=True)
    memo = models.TextField(default='')
    link = models.CharField(max_length=250,null=True,blank=True)
    youtube = models.CharField(max_length=250,null=True,blank=True)
    youtube_length = models.IntegerField(default=0)
    file = models.FileField(blank=True,null=True)
    filename = models.CharField(max_length=60,null=True,blank=True)

teacher/views.py
from django.shortcuts import render
from teacher.models import *
from student.models import *
from account.models import *
from account.forms import *
from teacher.forms import *
from django.views import generic
from django.contrib.auth.models import User, Group
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, View, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
import django_excel as excel
from django.http import JsonResponse
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
import os
from uuid import uuid4
from django.conf import settings
from wsgiref.util import FileWrapper
from io import StringIO
from shutil import copyfile
from django.http import HttpResponse
#from django.urls import reverse

# 判斷是否為授課教師
def is_teacher(user, classroom_id):
    return user.groups.filter(name='teacher').exists() and Classroom.objects.filter(teacher_id=user.id, id=classroom_id).exists()

def is_assistant(user, classroom_id):
    assistants = Assistant.objects.filter(classroom_id=classroom_id, user_id=user.id)
    if len(assistants)>0 :
        return True
    return False	

class ClassroomList(generic.ListView):
    model = Classroom
    ordering = ['-id']
    paginate_by = 3   
    
class ClassroomCreate(CreateView):
    model = Classroom
    fields = ["levels", "domains", "name", "password"]
    success_url = "/teacher/classroom"   
    template_name = 'teacher/classroom_form.html'
      
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.teacher_id = self.request.user.id
        self.object.domains = self.request.POST.getlist('domains')
        self.object.levels = self.request.POST.getlist('levels')	
        self.object.save()
        # 將教師設為0號學生
        enroll = Enroll(classroom_id=self.object.id, student_id=self.request.user.id, seat=0)
        enroll.save()   
        return redirect("/teacher/classroom")   
			
    def get_context_data(self, **kwargs):
        context = super(ClassroomCreate, self).get_context_data(**kwargs)
        context['domains'] = Domain.objects.all()
        context['levels'] = Level.objects.all()
        return context
    
class ClassroomUpdate(UpdateView):
    model = Classroom
    fields = ["levels", "domains", "name", "password"]
    success_url = "/teacher/classroom"   
    template_name = 'teacher/classroom_form.html'
    
    def get_context_data(self):
        context = super(ClassroomUpdate, self).get_context_data()
        context['domains'] = Domain.objects.all()
        context['levels'] = Level.objects.all()
        return context    
    
#新增一個公告
class AnnounceCreate(LoginRequiredMixin, CreateView):
    model = Message
    form_class = LineForm
    success_url = '/account/dashboard/0'    
    template_name = 'teacher/announce_form.html'     

    def form_valid(self, form):
        valid = super(AnnounceCreate, self).form_valid(form)
        self.object = form.save(commit=False)
        classroom = Classroom.objects.get(id=self.kwargs['classroom_id'])
        self.object.title = u"[公告]" + classroom.name + ":" + self.object.title
        self.object.author_id = self.request.user.id
        self.object.save()
        # 訊息
        enrolls = Enroll.objects.filter(classroom_id=self.kwargs['classroom_id'])
        for enroll in enrolls :
            messagepoll = MessagePoll(message_id=self.object.id, reader_id=enroll.student_id)
            messagepoll.save()              
        return valid
      
    # 限本班教師
    def render_to_response(self, context):
        teacher_id = Classroom.objects.get(id=self.kwargs['classroom_id']).teacher_id
        if not teacher_id == self.request.user.id:
            return redirect('/')
        return super(AnnounceCreate, self).render_to_response(context)       
      
    def get_context_data(self, **kwargs):
        context = super(AnnounceCreate, self).get_context_data(**kwargs)
        context['classroom'] = Classroom.objects.get(id=self.kwargs['classroom_id'])
        return context	
      
# 教師可以查看所有帳號
class StudentList(ListView):
    context_object_name = 'users'
    paginate_by = 50
    template_name = 'teacher/student_list.html'

    def get_queryset(self):
        username = username__icontains=self.request.user.username+"_"
        if self.request.GET.get('account') != None:
            keyword = self.request.GET.get('account')
            queryset = User.objects.filter(Q(username__icontains=username+keyword) | (Q(first_name__icontains=keyword) & Q(username__icontains=username))).order_by('-id')
        else :
            queryset = User.objects.filter(username__icontains=username).order_by('-id')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(StudentList, self).get_context_data(**kwargs)
        account = self.request.GET.get('account')
        context.update({'account': account})
        return context
      
#匯入帳號檔案
class StudentUpload(View):
    form_class = UploadFileForm
    success_url = 'import_student'
    template_name = 'teacher/student_upload.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            ImportUser.objects.all().delete()
            request.FILES['file'].save_to_database(
                name_columns_by_row=0,
                model=ImportUser,
                mapdict=['username', 'first_name', 'password'])
            users = ImportUser.objects.all()
            return render(self.request, 'teacher/student_import.html',{'users':users})
        else:
            return HttpResponseBadRequest()
          
#建立學生帳號
class StudentImport(LoginRequiredMixin, RedirectView):

    def get(self, request, *args, **kwargs):
        users = ImportUser.objects.all()
        username_list = [request.user.username+"_"+user.username for user in users]
        exist_users = [user.username for user in User.objects.filter(username__in=username_list)]
        create_list = []
        for user in users:
            username = request.user.username+"_"+user.username
            if username in exist_users:
                continue
            new_user = User(username=username, first_name=user.first_name, last_name=request.user.last_name, password=user.password, email=username+"@edu.tw")
            new_user.set_password(user.password)
            create_list.append(new_user)

        User.objects.bulk_create(create_list)
        new_users = User.objects.filter(username__in=[user.username for user in create_list])

        profile_list = []
        message_list = []
        poll_list = []
        title = "請洽詢任課教師課程名稱及選課密碼"
        url = "/student/classroom/add"
        message = Message(title=title, url=url, time=timezone.now())
        message.save()
        for user in new_users:
            profile = Profile(user=user)
            profile_list.append(profile)
            poll = MessagePoll(message_id=message.id, reader_id=user.id)
            poll_list.append(poll)

        Profile.objects.bulk_create(profile_list)
        MessagePoll.objects.bulk_create(poll_list)
        return super(StudentImport, self).get(self, request, *args, **kwargs)        
        
    def get_redirect_url(self, *args, **kwargs):
        #TaxRate.objects.get(id=int(kwargs['pk'])).delete()   
        return '/teacher/student/list'

# 列出所有課程
class GroupList(ListView):
    model = Group
    context_object_name = 'groups'
    template_name = 'teacher/group.html'
    paginate_by = 25
    def get_queryset(self):      
        queryset = ClassroomGroup.objects.filter(classroom_id=self.kwargs['classroom_id']).order_by("-id")
        return queryset
			
    def get_context_data(self, **kwargs):
        context = super(GroupList, self).get_context_data(**kwargs)
        context['classroom_id'] = self.kwargs['classroom_id']
        return context				
			
#新增一個分組
class GroupCreate(CreateView):
    model = ClassroomGroup
    form_class = GroupForm
    template_name = 'teacher/group_form.html'    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.classroom_id = self.kwargs['classroom_id']
        if is_teacher(self.request.user, self.kwargs['classroom_id']) or is_assistant(self.request.user, self.kwargs['classroom_id']):
            self.object.save()
            # 隨機分組
            if form.cleaned_data['assign'] == 1:
                enrolls = Enroll.objects.filter(classroom_id=self.kwargs['classroom_id'], seat__gt=0).order_by('?')
                number = 0
                for enroll in enrolls:
                    group = StudentGroup(group_id=self.object.id, enroll_id=enroll.id, group=(number % self.object.numbers))
                    group.save()
                    number += 1
                self.object.opening=False
                self.object.save()
                
        return redirect("/student/group/panel/"+ str(self.object.id))   
			
    def get_context_data(self, **kwargs):
        context = super(GroupCreate, self).get_context_data(**kwargs)
        return context	
			
class GroupUpdate(UpdateView):
    model = ClassroomGroup
    form_class = GroupForm2		
    template_name = 'form.html'
    def get_success_url(self):
        succ_url =  '/student/group/list/'+self.kwargs['pk']
        return succ_url
			
    def form_valid(self, form):
        if is_teacher(self.request.user, self.kwargs['classroom_id']) or is_assistant(self.request.user, self.kwargs['classroom_id']):
            group = ClassroomGroup.objects.get(id=self.kwargs['pk'])
            reduce = group.numbers - form.cleaned_data['numbers']
            if reduce > 0:
                for i in range(reduce):

teacher/templates/teacher/announce_form.html
{% extends "base.html" %}

{% load tag %}
{% block content %}
        <h1>公告班級：{{classroom.name}}</h1>
         <form action="" enctype="multipart/form-data"  method="post">
            <table class="table">
                {{ form.as_table }}       
            <tr><td></td><td><input id="submit" type="submit" value="送出"><td</tr>
            </table>
            {% csrf_token %}

        </form>
{% endblock %}

teacher/templates/teacher/assistant.html
{% extends "base.html" %}
{% load tag %}
{% block content %}
<a href="/teacher/classroom/" class="btn btn-success" role="btn">{{classroom.name}}</a>
<a href="/teacher/classroom/assistant/add/{{classroom.id}}" class="btn btn-warning" role="btn"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> 設定助教</a>
        <table class="table">
            <td>帳號</td>
        </tr>
{% for assistant in assistants %}
            <tr>
                <td>{{assistant.user_id|realname}}</td>
            </tr>
{% endfor %}
</table>
{% endblock %}

teacher/templates/teacher/assistant_user.html
{% extends "base.html" %}
{% block title %} Teachers {% endblock %}
{% block content %}
    <form action=""  method="get">
      <p>
       <a href="/teacher/classroom/assistant/{{classroom.id}}" class="btn btn-success" role="btn">{{classroom.name}}</a>
 
       搜尋帳號：<input type="text" name = "account"><input type="submit" value="送出"/>  
      </p>
    </form>
        <tr>
          
        <table class="table">
            <td>帳號</td>
            <td>姓名</td>
            <td>最新登入</td>
            <td>功能</td>
        </tr>
        {% for user in users %}
            <tr>
                <td>{{user.username}}</td>
                <td>{{user.first_name}}</td>
                <td>{{user.last_login}}</td>
                <td>
                {% if user.id in assistants  %}<a href="#" data-classroomid="{{classroom.id}}" data-userid="{{ user.id }}" data-action="unset" class="assistant btn btn-info" role="button">取消助教</a>{% else %}<a href="#" data-classroomid="{{classroom.id}}" data-userid="{{ user.id }}" data-action="set" class="assistant btn btn-light" role="button">設為助教</a>{% endif %}
            </tr>
        {% endfor %}
        </table>
        {% load pagination %}
        {% get_pagination %}  
{% endblock %}

{% block domready %}
  $('a.assistant').click(function(e){
    var launcher = this;  
    e.preventDefault();
    $.post('/teacher/assistant/make/',
      {
        userid: $(launcher).data('userid'),
        classroomid: $(launcher).data('classroomid'),
        action: $(launcher).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $(launcher).data('action');
		      if (previous_action == 'set') {
               $(launcher).removeClass("btn-light").addClass("btn-info");
               $(launcher).blur();
               $(launcher).html("取消助教");
               $(launcher).data('action', 'unset');
           } else {
               $(launcher).removeClass("btn-info").addClass("btn-light");
               $(launcher).html("設為助教");
               $(launcher).data('action', 'set');               
           }
        } else {
			   	alert("hello");
	    	}
      }
    );
  });
{% endblock %}

teacher/templates/teacher/classroom_form.html
{% extends "base.html" %}
{% load tag %}
{% block header %}
<link href="/static/styles/checkbox.css" rel="stylesheet" type="text/css" media="all">
{% endblock %}
{% block content %}
         <form action="" enctype="multipart/form-data"  method="post">
            <table class="table">
           <tr><th nowrap>年級:</td>
                <td>
              {% for level in levels %}
         <label for="level{{forloop.counter}}" class="customcheck">{{level.title}}
           <input {% if level.id|int_to_str in classroom.levels %}checked="checked"{% endif %} value="{{level.id}}" name="levels" type="checkbox" id="level{{forloop.counter}}" class="checkmark">
           <span class="checkmark"></span>
        </label>
                  {% endfor %}
              </td>             
              <tr><th nowrap>學習領域:</td>
                <td>
              {% for domain in domains %}
          <label for="domain{{forloop.counter}}" class="customcheck">{{domain.title}}
           <input {% if domain.id|int_to_str in classroom.domains %}checked="checked"{% endif %} value="{{domain.id}}" name="domains" type="checkbox" id="domain{{forloop.counter}}" class="checkmark">
           <span class="checkmark"></span>
        </label>             
              {% endfor %}
              </td>
              </tr>

                <tr><th><label for="id_name">班級名稱:</label></th><td><input class="form-control list-group-item-text" id="id_name" maxlength="30" name="name" type="text" value="{{classroom.name}}"/></td></tr>
<tr><th><label for="id_password">選課密碼:</label></th><td><input class="form-control list-group-item-text" id="id_password" maxlength="30" name="password" type="text" value="{{classroom.password}}"/></td></tr>
            </table>
            {% csrf_token %}
            <input type="submit" value="送出">
        </form>
{% endblock %}

teacher/templates/teacher/classroom_list.html
{% extends "base.html" %}
{% load tag %}
{% block content %}
<a href="/teacher/classroom/create" class="btn btn-info"><i class="fa fa-hand-o-right"></i> 新增班級</a>
<a href="/teacher/student/list" class="btn btn-info"><i class="fa fa-hand-o-right"></i> 學生帳號</a>
{% for classroom in classroom_list %}
<div class="card">
  <div class="card-header">
   {{classroom.name}} ({{classroom.password}})
  </div>
  <div class="card-body">
    <a href="/teacher/classroom/{{classroom.id}}/update" class="btn btn-light"><i class="fa fa-star"></i>修改</a>
    <a href="/student/classroom/{{classroom.id}}/classmate" class="btn btn-light"><i class="fa fa-search-plus"></i>學生</a>
    <a href="/teacher/classroom/assistant/{{classroom.id}}" class="btn btn-light"><i class="fa fa-male"></i>助教</a>
    <a href="/teacher/group/{{classroom.id}}" class="btn btn-secondary"><i class="fa fa-street-view"></i>分組</a>
    <a href="/" class="btn btn-secondary"><i class="fa fa-bullhorn"></i>公告</a>   
    <a href="/teacher/forum/{{classroom.id}}" class="btn btn-success"><i class="fa fa-commenting"></i>討論區</a>  
    <a href="/" class="btn btn-success"><i class="fa fa-cogs"></i>思辨區</a>    
    <a href="/" class="btn btn-success"><i class="fa fa-cubes"></i>合作區</a>    
    <a href="/" class="btn btn-success"><i class="fa fa-flag"></i>測驗區</a>     
  </div>
</div>
{% endfor %}
    {% load pagination %}
    {% get_pagination %}
{% endblock %}

teacher/templates/teacher/forum_class.html
{% extends "base.html" %}
{% load tag %}
{% block header %}
<link href="/static/styles/switch.css" rel="stylesheet" type="text/css" media="all">	
{% endblock %}
{% block content %}
<button type="button" class="btn btn-success">{{fwork.title}}</button>
<div class="row">
        {% for classroom, open, deadline, deadline_date in classrooms %}
<div class="col col-xs-12 col-sm-4 col-md-3">
  <div class="card">
    <div class="card-header">
   {{classroom.id|classname}}
    </div>
    <div class="card-body">
      <div class="anil_nepal">
      <label class="switch switch-left-right">        
        <input data-forumid="{{forum_id}}" data-classroomid="{{classroom.id}}" type="checkbox" name="onoffswitch" class="switch-input" id="myonoffswitch{{classroom.id}}" {% if open %}checked{% endif %}>   
        <span class="switch-label" data-on="開啟" data-off="關閉"></span> <span class="switch-handle"></span> </label>
        <div>
                <a href="/teacher/forum/deadline/{{classroom.id}}/{{forum_id}}">期限:{% if deadline %}{{deadline_date|date:"Y/m/d H:i:s"}}{% else %}無{% endif %}</a>
        </div>

       </div>         
    </div>
  </div>
</div>
        {% endfor %}
</div>
{% endblock %}
{% block domready %}
{% for classroom, open, deadline, deadline_date in classrooms %}
    $('#myonoffswitch{{classroom.id}}').click(function(e){
    var launcher = this;  
    e.preventDefault();
    $.post('/teacher/forum/class/switch/',
      {
        forumid: $(launcher).data('forumid'),
        classroomid: $(launcher).data('classroomid'),
        status: $(launcher).is(":checked"),
      },
      function(data){

          if (data['status'] == 'true') {
              //alert('開放討論主題');
              $(launcher).prop("checked", true);
          } else {
              //alert('關閉討論主題');
              $(launcher).prop("checked", false);
          }

      }
    );
    });
{% endfor %}

	{% endblock %}

teacher/templates/teacher/forum_form.html
{% extends "base.html" %}
{% load tag %}
{% block header %}
<link href="/static/styles/checkbox.css" rel="stylesheet" type="text/css" media="all">
{% endblock %}
{% block content %}
         <form action="" enctype="multipart/form-data"  method="post">
            <table class="table">
           <tr><th nowrap>年級:</td>
                <td>
              {% for level in levels %}
         <label for="level{{forloop.counter}}" class="customcheck">{{level.title}}
           <input {% if level.id|int_to_str in classroom.levels %}checked="checked"{% endif %} value="{{level.id}}" name="levels" type="checkbox" id="level{{forloop.counter}}" class="checkmark">
           <span class="checkmark"></span>
        </label>
                  {% endfor %}
              </td>             
              <tr><th nowrap>學習領域:</td>
                <td>
              {% for domain in domains %}
          <label for="domain{{forloop.counter}}" class="customcheck">{{domain.title}}
           <input {% if domain.id|int_to_str in classroom.domains %}checked="checked"{% endif %} value="{{domain.id}}" name="domains" type="checkbox" id="domain{{forloop.counter}}" class="checkmark">
           <span class="checkmark"></span>
        </label>             
              {% endfor %}
              </td>
              </tr>
              
<tr><th nowrap>班級:</th><Td>
              {% for classroom in classrooms %}
  <label for="class{{forloop.counter}}" class="customcheck">{{classroom.name}}
           <input {% if classroom.id == classroom_id %}checked="checked"{% endif %} value="{{classroom.id}}" name="classrooms" type="checkbox" id="classroom{{forloop.counter}}" class="checkmark">
           <span class="checkmark"></span>
        </label> 
              {% endfor %}
  </TD></tr>
            <tr><th><label for="id_title">討論主題:</label></th><td><input class="form-control list-group-item-text" id="id_title" maxlength="250" name="title" type="text" value="{{fwork.title}}"/>
  </table>
           
            {% csrf_token %}
            <input type="submit" value="送出">
        </form>
{% endblock %}

teacher/templates/teacher/student_import.html
{% extends "base.html" %}
{% block content %}
<a href="/teacher/import/student" class="btn btn-warning" role="btn">建立帳號</a>
<table class="table">
  <tr>
  <td>帳號</td>
  <td>姓名</td>
  <td>密碼</td>
  </tr>
{% for user in users %}  
  <tr>
  <td>{{user.username}}</td>
  <td>{{user.first_name}}</td>
  <td>{{user.password}}</td>
  </tr>

{% endfor %}
</table>

{% endblock %}

teacher/templates/teacher/student_upload.html
{% extends "base.html" %}
{% block content %}
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <a href="/static/files/sample.xls" class="btn btn-warning" role="btn">格式範本.xls</a>
    <form action="" enctype="multipart/form-data"  method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" class="btn-info" value="送出">
    </form>
{% endblock %}