account/urls.py
# -*- coding: utf8 -*-
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('dashboard/<int:action>',  views.MessageList.as_view()),
    path('login/<int:role>', views.Login.as_view()),
    path('logout/', views.Logout.as_view()),  
    path('user/', views.UserList.as_view()),
    path('user/create/', views.UserCreate.as_view()),    
    path('user/<int:pk>', views.UserDetail.as_view()),
    path('user/<int:pk>/update/', views.UserUpdate.as_view()), 
    path('user/<int:pk>/password/', views.UserPasswordUpdate.as_view()), 
    path('user/<int:pk>/teacher/', views.UserTeacher.as_view()),    
    #註冊學校
    path('school/create/', views.SchoolCreate.as_view()), 
    #私訊
    path('line/classmate/<int:classroom_id>/', views.LineClassmateList.as_view()),      
    path('line/<int:user_id>/<int:classroom_id>/create/', views.LineCreate.as_view()), 
    path('line/<int:pk>/', views.LineDetail.as_view()),    
]

bioread/urls.py
# -*- coding: utf8 -*-
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="homepage.html")),
    path('account/', include('account.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('annotate/', include('annotate.urls')),
]

account/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User

class County(models.Model):
  name = models.CharField(max_length=20)
  mapx = models.IntegerField(default=0)	
  mapy = models.IntegerField(default=0)	
  
  def __unicode__(self):
      return self.name
    
class Zone(models.Model):
  name = models.CharField(max_length=20)
  county = models.IntegerField(default=0)
  
  def __unicode__(self):
      return self.name  

class School(models.Model):
  county = models.IntegerField(default=0)
  zone = models.IntegerField(default=0)
  system = models.IntegerField(default=0)
  name = models.CharField(max_length=50)
  online = models.BooleanField(default=True)

  def __unicode__(self):
      return self.name  
    
# 個人檔案資料
class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
	# 積分：上傳作業
  work = models.IntegerField(default=0)
	# 積分：擔任小老師
  assistant = models.IntegerField(default=0)
	# 積分：創意秀
  creative = models.IntegerField(default=0)	
	# 積分：按讚
  like = models.FloatField(default=0.0)
	# 積分：留言
  reply = models.FloatField(default=0.0)
	# 大頭貼等級
  avatar = models.IntegerField(default=0)
	# 訪客人次
  home_count = models.IntegerField(default=0)
  visitor_count = models.IntegerField(default=0)
	# 開站時間
  open_time = models.DateTimeField(auto_now_add=True)

 
  def __unicode__(self):
    return str(self.user.username)
  

# 積分記錄 
class PointHistory(models.Model):
    # 使用者序號
	user_id = models.IntegerField(default=0)
	# 積分類別 1:上傳作業 2:小老師
	kind = models.IntegerField(default=0)
	# 積分項目
	message = models.CharField(max_length=100)	
	# 將積分項目超連結到某個頁面
	url = models.CharField(max_length=100)
	# 記載時間 
	publish = models.DateTimeField(default=timezone.now)

	def __unicode__(self):
		return str(self.user_id)
  
# 大廳訊息	
class Message(models.Model):
    author_id = models.IntegerField(default=0)
    reader_id = models.IntegerField(default=0)
    type = models.IntegerField(default=0)
    classroom_id = models.IntegerField(default=0)
    title = models.CharField(max_length=250)
    content = models.TextField(default='')
    url = models.CharField(max_length=250)
    time = models.DateTimeField(auto_now_add=True)

    #def __str__(self):
    #    return self.title
		
    @classmethod
    def create(cls, title, url, time):
        message = cls(title=title, url=url, time=time)
        return message
      
# 訊息    
class MessagePoll(models.Model):
    message_type = models.IntegerField(default=0)  
    message_id = models.IntegerField(default=0)
    reader_id = models.IntegerField(default=0)
    classroom_id = models.IntegerField(default=0)
    read = models.BooleanField(default=False)
    
    @property
    def message(self):
        return Message.objects.get(id=self.message_id)        

class MessageFile(models.Model):
    message_id = models.IntegerField(default=0) 
    filename = models.TextField()
    before_name = models.TextField()
    upload_date = models.DateTimeField(default=timezone.now)

class MessageContent(models.Model):
    message_id =  models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    title =  models.CharField(max_length=250,null=True,blank=True)
    filename = models.CharField(max_length=250,null=True,blank=True)    
    publication_date = models.DateTimeField(default=timezone.now)

# 訪客 
class Visitor(models.Model):
    date = models.IntegerField(default=0)
    count = models.IntegerField(default=0)
    
# 訪客記錄
class VisitorLog(models.Model):
    visitor_id = models.IntegerField(default=0)    
    user_id = models.IntegerField(default=0)
    IP = models.CharField(max_length=20, default="")
    time = models.DateTimeField(auto_now_add=True)		    
    
    @property        
    def user(self):
        return User.objects.get(id=self.user_id)       
		
#課程計數器
class LessonCounter(models.Model):
	name = models.CharField(max_length=10)
	hit = models.IntegerField(default=0)
	
#日期計數器
class DayCounter(models.Model):
	day = models.CharField(max_length=8)
	hit = models.IntegerField(default=0)	
	
#計數器記錄
class LogCounter(models.Model):
	counter_id = models.IntegerField(default=0)
	counter_date = models.DateTimeField(default=timezone.now)
	counter_ip = models.CharField(max_length=20)
  
#教師申請
class TeacherApply(models.Model):
  user_id = models.IntegerField(default=0)
  approver = models.IntegerField(default=0)
  memo = models.TextField()
  file =  models.FileField()
  
# 學習領域
class Domain(models.Model):
	title = models.CharField(max_length=200, default="",verbose_name= '領域名稱')
	
# 年級
class Level(models.Model):
  title = models.CharField(max_length=200, default="",verbose_name= '年級')

account/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User, Group
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, FormView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from account.forms import *
from account.models import *
from account.zone import *
from django.utils import timezone
from django.utils.timezone import localtime
from student.models import *
from django.contrib.auth import authenticate, login

class Login(FormView):
    success_url = '/account/dashboard/0'
    form_class = LoginForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "login.html"

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(Login, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):         
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']         
        if self.kwargs['role'] == 0:	
            user = authenticate(username=username, password=password)
        else:
            teacher = form.cleaned_data['teacher']					
            user = authenticate(username=teacher+"_"+username, password=password)   
        if user is not None:
            auth_login(self.request, user)
        else :
            return redirect("/account/login/"+str(self.kwargs['role']))
        if user.id == 1 and user.first_name == "":          
            user.first_name = "管理員"
            user.save()
            
            # 學習領域
            domains = ['生物']
            for domain_name in domains:
                domain = Domain(title=domain_name)
                domain.save()
            levels = ['高一','高二','高三']
            for level_name in levels:
                level = Level(title=level_name)
                level.save()            
            zones = Zone.objects.all()
            if len(zones) == 0:
                for city_name, zones, mapx, mapy in county:
                    city = County(name=city_name, mapx=mapx, mapy=mapy)
                    city.save()
                    for zone_name in zones:
                        zone = Zone(name=zone_name, county=city.id)
                        zone.save()
                school = School(county=2, zone=38, system=3, name="南港高中")
                school.save()
                user.last_name = "1"
                user.save()
                try :
                    group = Group.objects.get(name="apply")	
                except ObjectDoesNotExist :
                    group = Group(name="apply")
                    group.save()                                         
                group.user_set.add(user)														
                # create Message
                title = "請修改您的姓名"
                url = "/account/realname"
                message = Message(title=title, url=url, time=timezone.now())
                message.save()                        
                    
                # message for group member
                messagepoll = MessagePoll(message_id = message.id,reader_id=1)
                messagepoll.save() 														
        # 記錄訪客資訊
        admin_user = User.objects.get(id=1)
        try:
            profile = Profile.objects.get(user=admin_user)
        except ObjectDoesNotExist:
            profile = Profile(user=admin_user)
            profile.save()
        profile.visitor_count = profile.visitor_count + 1
        profile.save()
                                    
        year = localtime(timezone.now()).year
        month =  localtime(timezone.now()).month
        day =  localtime(timezone.now()).day
        date_number = year * 10000 + month*100 + day
        try:
            visitor = Visitor.objects.get(date=date_number)
        except ObjectDoesNotExist:
            visitor = Visitor(date=date_number)
        visitor.count = visitor.count + 1
        visitor.save()
                                        
        visitorlog = VisitorLog(visitor_id=visitor.id, user_id=user.id, IP=self.request.META.get('REMOTE_ADDR'))
        visitorlog.save()                 
          
        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(Login, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        #if not is_safe_url(url=redirect_to, host=self.request.get_host()):
        #    redirect_to = self.success_url
        return redirect_to

    def get_form_class(self):
        if self.kwargs['role'] == 0:
            return LoginForm
        else :
            return LoginStudentForm
      
class Logout(RedirectView):
    url = '/account/login/0'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(Logout, self).get(request, *args, **kwargs)
              
class SuperUserRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect("/account/login/0")
        return super(SuperUserRequiredMixin, self).dispatch(request,
            *args, **kwargs)

class UserList(SuperUserRequiredMixin, generic.ListView):
    model = User
    ordering = ['-id']
    paginate_by = 3    

class UserDetail(LoginRequiredMixin, generic.DetailView):
    model = User
    
class UserCreate(CreateView):
    model = User
    form_class = UserRegistrationForm
    success_url = "/account/login/0"   
    #template_name = 'user_create.html'
      
    def form_valid(self, form):
        valid = super(UserCreate, self).form_valid(form)
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data.get('password'))
        new_user.save()  
        profile = Profile(user=new_user)
        profile.save()  
        try :
            group = Group.objects.get(name="apply")	
        except ObjectDoesNotExist :
            group = Group(name="apply")
            group.save()                                         
        group.user_set.add(new_user)        
        return valid
      
    def get_context_data(self, **kwargs):
        context = super(UserCreate, self).get_context_data(**kwargs)
        context['schools'] = School.objects.all()
        return context

class UserUpdate(SuperUserRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = "/account/user"   
    template_name = 'form.html'
    
class UserPasswordUpdate(SuperUserRequiredMixin, UpdateView):
    model = User
    form_class = UserPasswordForm
    success_url = "/account/user"   
    template_name = 'form.html'
    
    def form_valid(self, form):
        valid = super(UserPasswordUpdate, self).form_valid(form)
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data.get('password'))
        new_user.save()  
        return valid   

class UserTeacher(SuperUserRequiredMixin, FormView):
    success_url = '/account/user'
    form_class = UserTeacherForm
    template_name = "form.html"
      
    def form_valid(self, form):
        valid = super(UserTeacher, self).form_valid(form)
        user = User.objects.get(id=self.kwargs['pk'])
        try :
            group = Group.objects.get(name="teacher")	
        except ObjectDoesNotExist :
            group = Group(name="teacher")
            group.save()        
        if form.cleaned_data.get('teacher') :
            group.user_set.add(user)
        else: 
            group.user_set.remove(user)
        return valid  
      
    def get_form_kwargs(self):
        kwargs = super(UserTeacher, self).get_form_kwargs()
        kwargs.update({'pk': self.kwargs['pk']})
        return kwargs
      
# 訊息
class MessageList(ListView):
    context_object_name = 'messages'
    paginate_by = 20
    template_name = 'dashboard.html'

    def get_queryset(self):             
        query = []
        #公告
        if self.kwargs['action'] == "1":
            messagepolls = MessagePoll.objects.filter(reader_id=self.request.user.id, message_type=1).order_by('-message_id')
        #私訊
        elif self.kwargs['action'] == "2":
            messagepolls = MessagePoll.objects.filter(reader_id=self.request.user.id, message_type=2).order_by('-message_id')
        #系統
        elif self.kwargs['action'] == "3":
            messagepolls = MessagePoll.objects.filter(reader_id=self.request.user.id, message_type=3).order_by('-message_id')						
        else :
            messagepolls = MessagePoll.objects.filter(reader_id=self.request.user.id).order_by('-message_id')
        for messagepoll in messagepolls:
            query.append([messagepoll, messagepoll.message])
        return query
        
    def get_context_data(self, **kwargs):
        context = super(MessageList, self).get_context_data(**kwargs)
        context['action'] = self.kwargs['action']
        return context

account/templates/dashboard.html
{% extends "base.html" %}
{% load tz %}
{% load tag %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<a href="/account/dashboard/0" class="btn btn-info{% if action == '0' %} active{% endif %}" role="btn"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> 所有訊息</a>
<a href="/account/dashboard/1" class="btn btn-info{% if action == '1' %} active{% endif %}" role="btn"><span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> 課程公告</a>
<a href="/account/dashboard/2" class="btn btn-info{% if action == '2' %} active{% endif %}" role="btn"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> 我的私訊</a>
<a href="/account/line/" class="btn btn-info" role="btn"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> 寄出私訊</a>
<Table class="table">
{% for messagepoll, message in messages %}<Tr><td>
 <button class="btn btn-default">
{{ message.time| date:"Y/m/d H:i"}}
  </button>
{% if message.url %}
<a href="{{message.url}}">
{% else %}
<a href="/account/line/{{ message.id }}">
{% endif %}
{% if message.type == 2 %}
<img src="/static/images/line.png">
{% elif message.type == 1 %}
<img src="/static/images/announce.png">
{% elif message.type == 3 %}
<img src="/static/images/system.png">
{% endif %}
{{ message.title}}
{% if message.title|img == "assistant"%}
<img src="/static/images/assistant.png">
{% elif message.title|img == "teacher" %}
<img src="/static/images/teacher.png">
{% elif message.title|img == "certificate" %}
<img src="/static/images/certificate.png">
{% endif %}
</a>

{% if not messagepoll.read %}
<img src="/static/images/new.gif">
{% endif %}
</Tr>
{% endfor %}
</Table>
        {% load pagination %}
        {% get_pagination %}         
{% endblock %}

account/templates/logged_out.html
{% extends "base.html" %}

{% block content %}
<p>您已登出!!</p>  
{% endblock %}

account/templates/login.html
{% extends "base.html" %}

{% block content %}
{% if form.errors %}
<p>帳號或密碼不符合，請再試一次。</p>
{% endif %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  　<input type="submit" class="btn btn-info" value="登入" />
</form>
{% endblock %}

account/templates/school.html
{% extends "base.html" %}
{% block header %}
    <script>    
    // 通常，當資料選項的變動性不大時，都會直接寫成 .js 檔含入即可。    
    var county = new Array();          
    var zone = new Array();
    var school_name = new Array();
    var school_id = new Array();
    {% for county, zone in district %}
       county[{{forloop.counter|add:-1}}] = [{{county.id}}, "{{county.name}}"];
       zone[{{forloop.counter|add:-1}}] = new Array();
       school_name[{{forloop.counter|add:-1}}] = new Array();     
       school_id[{{forloop.counter|add:-1}}] = new Array();      
       {% for q in zone %}
           zone[{{forloop.parentloop.counter|add:-1}}][{{forloop.counter|add:-1}}] =  [{{q.0.id}}, "{{q.0.name}}"];
           school_name[{{forloop.parentloop.counter|add:-1}}][{{forloop.counter|add:-1}}] = new Array();
           school_id[{{forloop.parentloop.counter|add:-1}}][{{forloop.counter|add:-1}}] = new Array();        
           {% for r in q.1 %}
               school_name[{{forloop.parentloop.parentloop.counter|add:-1}}][{{forloop.parentloop.counter|add:-1}}][{{forloop.counter|add:-1}}] = "{{r.name}}";
               school_id[{{forloop.parentloop.parentloop.counter|add:-1}}][{{forloop.parentloop.counter|add:-1}}][{{forloop.counter|add:-1}}] = "{{r.id}}";            
           {% endfor %}
       {% endfor %}
    {% endfor %}
    // 載入 master 選單，同時初始化 detail 選單內容    
    function loadMaster( master, detail, school ) 
    {    
      master.options.length = county.length;    
      for( i = 0; i < county.length; i++ ) 
      {    
        master.options[ i ] = new Option( county[i][1], county[i][0] );  
        // Option( text , value );    
      }    
      master.selectedIndex = {{school.county}}-1;    
      doNewMaster( master, detail, school );    
      doNewDetail( master, detail, school );
    }    
    // 當 master 選單異動時，變更 detail 選單內容    
    function doNewMaster( master, detail, school) {    
      detail.options.length = zone[ master.selectedIndex ].length;    
   
      for( i = 0; i < zone[ master.selectedIndex ].length; i++ ) 
      {    
        detail.options[ i ] = new Option( zone[ master.selectedIndex ][ i ][1],    
                                          zone[ master.selectedIndex ][ i ][0] );    
      }
      detail.selectedIndex = {{school.zone}}-1;         
      doNewDetail( master, detail, school );      
    }   
    // 當 detail 選單異動時，變更 school 內容    
    function doNewDetail( master, detail, schools) {     
      schools.options.length = school_name[ master.selectedIndex ][ detail.selectedIndex ].length;          
      for( i = 0; i < school_name[ master.selectedIndex ][ detail.selectedIndex ].length; i++ ) 
      {         
        schools.options[ i ] = new Option( school_name[ master.selectedIndex ][ detail.selectedIndex ][ i ],    
                                          school_id[ master.selectedIndex ][ detail.selectedIndex ][ i ] );    
      }
      schools.selectedIndex = {{school.id}}-1;        
    }     
</script>
{% endblock %}
{% block content %}
<body onload="loadMaster( document.getElementById( 'county' ), document.getElementById( 'zone' ) , document.getElementById( 'schools' ) );">
  <form action="." method="post">
<p><label for="id_last_name">學校名稱：</label>   <select class="form-control" name="county" id="county"     
        onChange="doNewMaster( document.getElementById( 'county' ),document.getElementById( 'zone' ), document.getElementById( 'schools' ));">    
   </select>    
   <select class="form-control" name="zone" id="zone" onChange="doNewDetail( document.getElementById( 'county' ),document.getElementById( 'zone' ), document.getElementById( 'schools' ));">    
   </select> 
    <select class="form-control" name="last_name" id="schools">
    </select>    
    </p>
                {% csrf_token %}   
    <p><input type="submit" value="送出"></p>
  </form>
  </form>
{% endblock %}

account/templates/school_create.html
{% extends "base.html" %}

{% block header %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script src="/static/register_helper.js"></script>
<script>
var school_pool = [
  {% for s in schools %}{id: {{ s.id }}, zid: {{ s.zone }}, name: "{{ s.name }}"}, 
  {% endfor %}
];
//---------------------------------------------------------------------------
function update_school_list() {
  var zid = parseInt($('#zone').val());
  var html = '';
  for (sid in school_pool) {
    school = school_pool[sid];
    if (school.zid == zid) {
      html += '<li class="btn btn-light">' + school.name + '</li> ';
    }
  }
  $('#school_list').html(html);
}
//---------------------------------------------------------------------------
$(document).ready(function() {
  reset_county();
})
</script>
{% endblock %}

{% block content %}
<form action="." method="post">
  {% csrf_token %}
  <table class="table table-sm">
    <tbody>
      <tr>
        <th>
          <label for="id_county">縣市:</label>
        </th>
        <td>
          <select class="form-control" name="county" id="county" onchange="reset_zone(); update_school_list();"></select>
        </td>
      </tr>
      <tr>
        <th>
          <label for="id_zone">區域:</label>
        </th>
        <td>
          <select class="form-control" name="zone" id="zone" onchange="update_school_list();"></select>
        </td>
      </tr>
      <tr>
        <th>
          <label for="id_system">學制:</label>
        </th>
        <td>
          <select class="form-control" name="system" id="id_system">
            <option value=0>國小</option>
            <option value=1>國中</option>
            <option value=2>高中</option>
            <option value=3>大學</option>     
          </select>       
        </td>
      </tr>
      <tr>
        <th>
          <label for="id_name">學校名稱:</label>
        </th>
        <td>
          <input id="id_name" maxlength="50" name="name" class="form-control" type="text">
        </td>
      </tr>
      <tr>
        <th></th>
        <td><div class="g-recaptcha" data-sitekey="6LfA4GYUAAAAANpI50rkKpLN_ZagC5C5AOjqjEsk"></div></td>
      </tr>
    </tbody>
  </table>
  <input class="form-control btn btn-info" type="submit" value="送出" />
</form>
<div id="comments">
  <h2>已註冊學校：</h2>
  <ul id="school_list" class="commentlist">
  </ul>
</div>
{% endblock %}